sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: I+jnih/qUDe9xnaIbgNPt6p/Lh95DBAmvkqc3dsat0ApnykOSie4/+nM+qJK0yatkxoZVteMdCnL6vY879rGexn0LekvGeRovGfqyN4Bj3tnf+PiDrBH6AQ25C0nbuDIWdpOlDqan+b6DcmsacOOO7rB1mwauadcfQX47MM5LSzSQEy8D7o1on1y0cglir2hbEhypyEtHV3l7FwXpdIPWmpzbNkQxma0Z7Eew/GY5NNpgH8PR8d9d+P9qpvdAkYoV0fxhJwBt4Rm47ve3vx++MWBXnrgX2eM+/rTIqt//sTr0uuYm3n33GOfWkQfTZV48BoEECflkkDHzPEtZIiAStAupabj1vzBEDKe22FQDrY+uJUS+y922bXzMffa6Stuzib0apwuCaJ14UBemXEtxV3kd+oR9VW+zdaFR5+5jJSc0FnU6YDHtUChm2XM/9kbEh9qjwTZVUknkCnISoaZIwdkpI2h4Ai1gsiCDx4BEthjJmJkL2E/1ST/WgddKLAbYMhefeLwKIrJR+cGpxE2+C5mt03XgvE+rcoxzOXES4yLdoP8x9Vi7rZHJnlfp44kCwzM4GmrG5lZC5oljL6Ryzl4FXUbv4xs82BrMoxHgLJm+b2jq4bWs4cfIUSwTcLZ18TuIlxo7shut2Yw7365RCMOCBZtxsbU71es65pnWPU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Wessex-Tales_3056
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy